<?php

# If PHP's memory limit is very low, some operations may fail.
#ini_set( 'memory_limit', '32M' );

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );


# SETTING SESSIONS FOR SOURCEFORGE
#  Note this will need to be removed (along with sessions directory) if migrate site away from sourceforge.
# session_save_path("/home/project-web/openemr/htdocs/sessions/");
#
# SETTINGS SESSIONS FOR SOURCEFORGE

require_once( "$IP/includes/DefaultSettings.php" );
#require_once("$IP/extensions/ConfirmAccount/SpecialConfirmAccount.php");
#require_once("$IP/extensions/MultiUpload/MultiUpload.php");
$wgMaxUploadFiles = 5;
#require_once( "$IP/extensions/PasswordReset/PasswordReset.php" );
#require_once( "$IP/extensions/googleAnalytics/googleAnalytics.php" );
#require_once("extensions/googleAnalytics/googa.php");
#require_once( "$IP/extensions/EmbedVideo/EmbedVideo.php" );
#require_once("$IP/extensions/ExpandTemplates/ExpandTemplates.php");
#require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );
wfLoadExtension( 'ParserFunctions' );
$wgPFEnableStringFunctions = true;

#require_once( $IP.'/extensions/Cite/Cite.php' );

#require_once("$IP/extensions/Renameuser/SpecialRenameuser.php");

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}

# Brady added below line in attempt to fix the inability to show resized large image files
$wgMaxShellMemory = 2202400;
# crossing fingers (it worked!!! :) )

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgServer           = "http://localhost:8080";
$wgSitename         = "OpenEMR Project Wiki";

# added to make the external links open new frames
$wgExternalLinkTarget = '_blank';

## Upload allows
$wgFileExtensions = array_merge($wgFileExtensions, array( 'pdf', 'txt', 'zip', 'tgz', 'gz', 'tar', 'odt', 'xlsx', 'docx', 'ico', 'svg' ));

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "";
$wgScriptExtension  = ".php";

## Help block vandals
$wgSquidServers = array('172.29.30.65', '172.29.30.66', '172.29.30.67', '172.29.30.68', '172.29.30.69', '172.29.30.70');

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgScriptPath/Oemr_wiki_logo.jpg";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "hello@open-emr.org";
$wgPasswordSender = "hello@open-emr.org";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "db";
$wgDBname           = "mediawiki";
$wgDBuser           = "wiki";

## Email settings
$wgSMTP = array(
 'host'     => "127.0.0.1", //could also be an IP address
 'IDHost'   => "open-emr",
 'port'     => 25,
 'auth'     => false,
 'username' => "",
 'password' => ""
);

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

# Enable subpages in the main namespace
$wgNamespacesWithSubpages[NS_MAIN] = true;

/**
 * Permission keys given to users in each group.
 * All users are implicitly in the '*' group including anonymous visitors;
 * logged-in users are all implicitly in the 'user' group. These will be
 * combined with the permissions of all groups that a given user is listed
 * in in the user_groups table.
 *
 * Note: Don't set $wgGroupPermissions = array(); unless you know what you're
 * doing! This will wipe all permissions, and may mean that your users are
 * unable to perform certain essential tasks or access new functionality
 * when new permissions are introduced and default grants established.
 *
 * Functionality to make pages inaccessible has not been extensively tested
 * for security. Use at your own risk!
 *
 * This replaces wgWhitelistAccount and wgWhitelistEdit
 */
$wgGroupPermissions = array();
 
/** @cond file_level_code */
// Implicit group for all visitors
//$wgGroupPermissions['*']['createaccount']    = true;
$wgGroupPermissions['*']['read']             = true;
//$wgGroupPermissions['*']['edit']             = true;
//$wgGroupPermissions['*']['createpage']       = true;
//$wgGroupPermissions['*']['createtalk']       = true;
//$wgGroupPermissions['*']['writeapi']         = true;
//$wgGroupPermissions['*']['patrolmarks']      = false; // let anons see what was patrolled
 
// Implicit group for all logged-in accounts
$wgGroupPermissions['user']['move']             = true;
$wgGroupPermissions['user']['move-subpages']    = true;
$wgGroupPermissions['user']['move-rootuserpages'] = true; // can move root userpages
//$wgGroupPermissions['user']['movefile']         = true;     // Disabled for now due to possible bugs and security concerns
$wgGroupPermissions['user']['read']             = true;
$wgGroupPermissions['user']['edit']             = true;
$wgGroupPermissions['user']['createpage']       = true;
$wgGroupPermissions['user']['createtalk']       = true;
$wgGroupPermissions['user']['writeapi']         = true;
$wgGroupPermissions['user']['upload']           = true;
$wgGroupPermissions['user']['reupload']         = true;
$wgGroupPermissions['user']['reupload-shared']  = true;
$wgGroupPermissions['user']['minoredit']        = true;
$wgGroupPermissions['user']['purge']            = true; // can use ?action=purge without clicking "ok"
$wgGroupPermissions['user']['sendemail']        = true;
 
// Implicit group for accounts that pass $wgAutoConfirmAge
$wgGroupPermissions['autoconfirmed']['autoconfirmed'] = true;
 
// Users with bot privilege can have their edits hidden
// from various log pages by default
$wgGroupPermissions['bot']['bot']              = true;
$wgGroupPermissions['bot']['autoconfirmed']    = true;
$wgGroupPermissions['bot']['nominornewtalk']   = true;
$wgGroupPermissions['bot']['autopatrol']       = true;
$wgGroupPermissions['bot']['suppressredirect'] = true;
$wgGroupPermissions['bot']['apihighlimits']    = true;
$wgGroupPermissions['bot']['writeapi']         = true;
#$wgGroupPermissions['bot']['editprotected']    = true; // can edit all protected pages without cascade protection enabled

// Most extra permission abilities go to this group
$wgGroupPermissions['sysop']['block']            = true;
$wgGroupPermissions['sysop']['createaccount']    = true;
$wgGroupPermissions['sysop']['delete']           = true;
$wgGroupPermissions['sysop']['bigdelete']        = true; // can be separately configured for pages with > $wgDeleteRevisionsLimit revs
$wgGroupPermissions['sysop']['deletedhistory']   = true; // can view deleted history entries, but not see or restore the text
$wgGroupPermissions['sysop']['deletedtext']      = true; // can view deleted revision text
$wgGroupPermissions['sysop']['undelete']         = true;
$wgGroupPermissions['sysop']['editinterface']    = true;
$wgGroupPermissions['sysop']['editusercss']      = true;
$wgGroupPermissions['sysop']['edituserjs']       = true;
$wgGroupPermissions['sysop']['import']           = true;
$wgGroupPermissions['sysop']['importupload']     = true;
$wgGroupPermissions['sysop']['move']             = true;
$wgGroupPermissions['sysop']['move-subpages']    = true;
$wgGroupPermissions['sysop']['move-rootuserpages'] = true;
$wgGroupPermissions['sysop']['patrol']           = true;
$wgGroupPermissions['sysop']['autopatrol']       = true;
$wgGroupPermissions['sysop']['protect']          = true;
$wgGroupPermissions['sysop']['proxyunbannable']  = true;
$wgGroupPermissions['sysop']['rollback']         = true;
$wgGroupPermissions['sysop']['trackback']        = true;
$wgGroupPermissions['sysop']['upload']           = true;
$wgGroupPermissions['sysop']['reupload']         = true;
$wgGroupPermissions['sysop']['reupload-shared']  = true;
$wgGroupPermissions['sysop']['unwatchedpages']   = true;
$wgGroupPermissions['sysop']['autoconfirmed']    = true;
$wgGroupPermissions['sysop']['upload_by_url']    = true;
$wgGroupPermissions['sysop']['ipblock-exempt']   = true;
$wgGroupPermissions['sysop']['blockemail']       = true;
$wgGroupPermissions['sysop']['markbotedits']     = true;
$wgGroupPermissions['sysop']['apihighlimits']    = true;
$wgGroupPermissions['sysop']['browsearchive']    = true;
$wgGroupPermissions['sysop']['noratelimit']      = true;
$wgGroupPermissions['sysop']['movefile']         = true;
$wgGroupPermissions['sysop']['unblockself']      = true;
$wgGroupPermissions['sysop']['suppressredirect'] = true;
#$wgGroupPermissions['sysop']['mergehistory']     = true;
$wgGroupPermissions['sysop']['confirmaccount']  = true;
$wgGroupPermissions['sysop']['passwordreset']   = true;
$wgGroupPermissions['sysop']['userrights']      = true;
$wgGroupPermissions['sysop']['confirmaccount']  = true;
$wgGroupPermissions['sysop']['renameuser']  = true;

// Permission to change users' group assignments
#$wgGroupPermissions['bureaucrat']['userrights']  = true;
$wgGroupPermissions['bureaucrat']['noratelimit'] = true;
#$wgGroupPermissions['bureaucrat']['confirmaccount'] = true;
$wgGroupPermissions['bureaucrat']['protect']     = true;
$wgGroupPermissions['bureaucrat']['editprotected']     = true;
// Permission to change users' groups assignments across wikis
#$wgGroupPermissions['bureaucrat']['userrights-interwiki'] = true;
// Permission to export pages including linked pages regardless of $wgExportMaxLinkDepth
#$wgGroupPermissions['bureaucrat']['override-export-depth'] = true;

$wgGroupPermissions['sysop']['deletelogentry']  = true;

$wgGroupPermissions['sysop']['deleterevision']  = true;
// To hide usernames from users and Sysops
$wgGroupPermissions['suppress']['hideuser'] = true;
// To hide revisions/log items from users and Sysops
$wgGroupPermissions['suppress']['suppressrevision'] = true;
// For private suppression log access
$wgGroupPermissions['suppress']['suppressionlog'] = true;

// Permission to disable user accounts
// Note that disabling an account is not reversible without a system administrator
// who has direct access to the database
#$wgGroupPermissions['bureaucrat']['disableaccount']  = true;

/**
 * The developer group is deprecated, but can be activated if need be
 * to use the 'lockdb' and 'unlockdb' special pages. Those require
 * that a lock file be defined and creatable/removable by the web
 * server.
 */
# $wgGroupPermissions['developer']['siteadmin'] = true;

// Inserted to allow zip
$wgMimeTypeBlacklist = array(
        # HTML may contain cookie-stealing JavaScript and web bugs
 'text/html', 'text/javascript', 'text/x-javascript',  'application/x-shellscript',
        # PHP scripts may execute arbitrary code on the server
 'application/x-php', 'text/x-php',
        # Other types that may be interpreted by some servers
 'text/x-python', 'text/x-perl', 'text/x-bash', 'text/x-sh', 'text/x-csh',
        # Client-side hazards on Internet Explorer
 'text/scriptlet', 'application/x-msdownload',
        # Windows metafile, client-side vulnerability on some systems
 'application/x-msmetafile',
        # A ZIP file may be a valid Java archive containing an applet which exploits the
 # same-origin policy to steal cookies
 #'application/zip',
        # MS Office OpenXML and other Open Package Conventions files are zip files
 # and thus blacklisted just as other zip files
 'application/x-opc+zip',
);

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

#$wgSecretKey = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':

#require_once "$IP/skins/openemr.php";
$wgDefaultSkin = 'openemr';
#$wgDefaultSkin = 'example';
#$wgDefaultSkin = 'monobook';
#$wgDefaultSkin = 'modern';
#$wgSkipSkins = array("chick", "cologneblue", "modern", "monobook", "myskin", "nostalgia", "simple", "standard", "vector");

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://www.gnu.org/copyleft/fdl.html";
$wgRightsText = "GNU Free Documentation License 1.3";
$wgRightsIcon = "${wgScriptPath}/skins/common/images/gnu-fdl.png";
# $wgRightsCode = "gfdl1_3"; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

# for upgrade
$wgShowExceptionDetails = true;

wfLoadSkin( 'Openemr' );
#wfLoadSkin( 'CologneBlue' );
#wfLoadSkin( 'Modern' );
#wfLoadSkin( 'MonoBook' );
#wfLoadSkin( 'Example' );

#require_once "$IP/extensions/GoogleAnalyticsLinks/GoogleAnalyticsLinks.php";

wfLoadExtension( 'EmbedVideo' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
#wfLoadExtension( 'CloudflarePurge' );

# CloudflarePurge config (you probably already have this)
#$wgCloudflarePurgeZoneID = 'your-zone-id';
#$wgCloudflarePurgeToken = 'your-api-token';

// Disable the page being hammered by DDoS
// $wgDisableSpecialPages['Recentchangeslinked'] = true;
//$wgReadOnly = "Wiki is temporarily in read-only mode due to maintenance.";
